// <auto-generated />
using System;
using DotNetWebApiWithRedis.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DotNetWebApiWithRedis.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6");

            modelBuilder.Entity("DotNetWebApiWithRedis.Models.Actor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Actor");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1975, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "male",
                            Name = "Bradley Cooper"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1989, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "female",
                            Name = "Brie Larson"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(1983, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "male",
                            Name = "Chris Hemsworth"
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(1981, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "male",
                            Name = "Chris Evans"
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(1979, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "male",
                            Name = "Chris Pratt"
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateTime(1974, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "male",
                            Name = "Leonardo DiCaprio"
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateTime(1975, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "female",
                            Name = "Kate Winslet"
                        },
                        new
                        {
                            Id = 8,
                            BirthDate = new DateTime(1978, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "female",
                            Name = "Zoë Saldaña"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
